#!/usr/bin/env python3
"""Scan R1/R2 FASTQ files to locate short barcode sequences.

The output helps users decide whether barcodes are present in R1 or R2,
whether they are anchored at position 0, and whether reverse-complement
matching should be considered.
"""

import argparse
import gzip
import json
from collections import Counter, defaultdict
from pathlib import Path


def normalize_seq(seq):
    return seq.strip().upper().replace("U", "T")


def revcomp(seq):
    table = str.maketrans("ACGTN", "TGCAN")
    return normalize_seq(seq).translate(table)[::-1]


def open_fastq(path):
    path = Path(path)
    if path.suffix == ".gz":
        return gzip.open(path, "rt")
    return path.open(encoding="utf-8", newline="")


def read_fastq(handle):
    while True:
        header = handle.readline()
        if not header:
            return
        seq = handle.readline().strip()
        handle.readline()
        qual = handle.readline()
        if not qual:
            return
        yield seq


def resolve_path(value, config_dir):
    path = Path(value).expanduser()
    if path.is_absolute():
        return path
    return (config_dir / path).resolve()


def load_from_config(config_path):
    config_path = Path(config_path).expanduser().resolve()
    config = json.loads(config_path.read_text(encoding="utf-8"))
    config_dir = config_path.parent
    r1 = resolve_path(config["input"]["r1"], config_dir)
    r2 = resolve_path(config["input"]["r2"], config_dir) if config["input"].get("r2") else None
    barcodes = []
    for sample in config.get("demux", {}).get("samples", []):
        for seq in sample.get("r1_primers", []) + sample.get("r2_primers", []):
            barcodes.append((sample["role"], normalize_seq(seq)))
    return r1, r2, barcodes


def scan(r1, r2, barcodes, max_reads, search_bases):
    counts = defaultdict(Counter)
    total = 0
    r1_handle = open_fastq(r1)
    r2_handle = open_fastq(r2) if r2 else None
    try:
        r1_iter = read_fastq(r1_handle)
        r2_iter = read_fastq(r2_handle) if r2_handle else None
        for r1_seq in r1_iter:
            r2_seq = next(r2_iter) if r2_iter else ""
            total += 1
            reads = {"R1": r1_seq, "R2": r2_seq}
            for role, barcode in barcodes:
                for label, candidate in [("forward", barcode), ("revcomp", revcomp(barcode))]:
                    for side, seq in reads.items():
                        if not seq:
                            continue
                        window = normalize_seq(seq[:search_bases])
                        pos = window.find(candidate)
                        if pos >= 0:
                            counts[(role, barcode)][(side, label, pos)] += 1
            if total >= max_reads:
                break
    finally:
        r1_handle.close()
        if r2_handle:
            r2_handle.close()
    return total, counts


def main():
    parser = argparse.ArgumentParser(description="Scan R1/R2 FASTQ files to locate short barcodes.")
    parser.add_argument("--config", help="Project JSON config generated by the web UI.")
    parser.add_argument("--r1")
    parser.add_argument("--r2")
    parser.add_argument("--barcode", action="append", default=[], help="role:sequence, for example modified:TAGCTTGT")
    parser.add_argument("--max-reads", type=int, default=200000)
    parser.add_argument("--search-bases", type=int, default=30)
    args = parser.parse_args()

    if args.config:
        r1, r2, barcodes = load_from_config(args.config)
    else:
        r1 = Path(args.r1)
        r2 = Path(args.r2) if args.r2 else None
        barcodes = []
        for item in args.barcode:
            role, seq = item.split(":", 1)
            barcodes.append((role, normalize_seq(seq)))

    total, counts = scan(r1, r2, barcodes, args.max_reads, args.search_bases)
    print(f"Scanned read pairs: {total}")
    print(f"Search window: first {args.search_bases} bases")
    for key in barcodes:
        role, barcode = key
        counter = counts.get(key, Counter())
        print(f"\n{role}  {barcode}")
        if not counter:
            print("  no hits")
            continue
        for (side, orientation, pos), count in counter.most_common(12):
            pct = count / total * 100 if total else 0
            print(f"  {side:2s} {orientation:7s} position={pos:<2d} count={count:<8d} {pct:6.3f}%")


if __name__ == "__main__":
    main()
